Module4 task1
htmlacademy-react/1783103-six-cities-14 pull request #4
Opened 2023-11-02 14:08 UTC by vostrStudy

1. добавлены исправления предидущего модуля
2. созданы и подключены моки офферам и отзывам
3. добавлены данные с работой по всем страницам
4. добавлены состояния компонента карточки
5. создана форма отправки комментария
6. страницы связаны между собой компонентом Link
Вопросы:
- не знаю как объявить тип элементам onHover

2023-11-02 16:56 UTC, romien94 commented on package.json
> +    "typescript-plugin-css-modules": "^5.0.2",
лучше залочить

2023-11-02 16:57 UTC, romien94 commented on src/components/app.tsx
> +function App({placesCount,offers,reviews}:AppMainPageProps): JSX.Element {
JSX.Element можно не указывать. Тайпскрипт понимает, что возвращается в tsx файлах

2023-11-02 16:58 UTC, romien94 commented on src/components/offers-page/offer-goods-array.tsx
> +function OfferGoodsArray(props:OfferGoodsArrayProps): JSX.Element {
снова JSX. деструктурировать можешь чуть выше.
можно сделать так 
{ currentOffer: { goods}  } : OfferGoodsArrayProps

2023-11-02 16:59 UTC, romien94 commented on src/components/offers-page/offer-goods-array.tsx
> +      {offerGoods.map((offerGood) => (
li должен быть внутри ul. он у тебя выше есть?

2023-11-02 17:00 UTC, romien94 commented on src/types/offers-types.ts
> +    host: OffersHost; //doesdeleteng the array brackets influence the outcome?//
не понял комментарий ))

2023-11-02 17:01 UTC, romien94 commented on src/pages/mainPage/main-page.tsx
> +  const {offers,placesCount} = props;
можно деструктуризовать сразу внутри круглых скобок ))

2023-11-02 17:01 UTC, romien94 commented on src/pages/favorites/favorites.tsx
> +                  {offers.map((offer:OffersType) => (
почему указала тип? он его должен автоматом подтягивать ))

2023-11-02 17:03 UTC, romien94 commented on src/mocks/offers-mocks.ts
> +      id: self.crypto.randomUUID(),
где self объявлен?

2023-11-02 17:04 UTC, romien94 commented on src/components/place-card/place-card.tsx
> +        <Link to= {`${AppRoute.Offer.replace(':offerId',id)}`}>
дважды повторяется один и тот же код с заменой offerId. мб, вынесешь его выше?

2023-11-02 17:05 UTC, romien94 requested changes
в целом, всё в порядке, оставил несколько комментариев. исправь линтовые ошибки

2023-11-03 07:29 UTC, vostrStudy commented on src/components/place-card/place-card.tsx
> +  onCardHover?: (offerId:OffersType['id']|null) => void; // need explanation
Я списала это из ретроспективы. напиши пожалуйста что это означает. Я так понимаю просто тип function нельзя писать

2023-11-03 07:30 UTC, vostrStudy commented on src/pages/favorites/favorites.tsx
> +                      // onCardHover = {handleCardHover}
А здесь если в Favorites  нужно тоже сделать hover,  не понимаю каким образом передавать handleCardHover?

2023-11-03 09:55 UTC, romien94 commented on src/pages/favorites/favorites.tsx
> +                      // onCardHover = {handleCardHover}
handleCardHover у тебя передаётся изнутри offer или из пропсов компонента?

2023-11-03 09:55 UTC, romien94 commented on src/components/place-card/place-card.tsx
> +  onCardHover?: (offerId:OffersType['id']|null) => void; // need explanation
почему. вполне себе можно оставить так
это означает, что функция в качестве аргумента принимает offerId или null, и ничего не возвращает (т.е. undefined)

2023-11-04 09:46 UTC, merged